// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe49PHpOcBBtB-Q01WM6BGpEqJDByIUQQ',
    appId: '1:529664366719:web:12892b3fd1d483e0d5074a',
    messagingSenderId: '529664366719',
    projectId: 'weldai-b9b25',
    authDomain: 'weldai-b9b25.firebaseapp.com',
    storageBucket: 'weldai-b9b25.firebasestorage.app',
    measurementId: 'G-2SQ9DZN6GT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQnyX5Jc4hlWO3aJQUur2aml8P6T3bCT8',
    appId: '1:529664366719:android:0e5b61c05189e1a4d5074a',
    messagingSenderId: '529664366719',
    projectId: 'weldai-b9b25',
    storageBucket: 'weldai-b9b25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBleXEZ0hamQK-1d7ez5vncVWYKFwtBs1g',
    appId: '1:529664366719:ios:645efa069815479cd5074a',
    messagingSenderId: '529664366719',
    projectId: 'weldai-b9b25',
    storageBucket: 'weldai-b9b25.firebasestorage.app',
    iosBundleId: 'com.example.firstly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBleXEZ0hamQK-1d7ez5vncVWYKFwtBs1g',
    appId: '1:529664366719:ios:645efa069815479cd5074a',
    messagingSenderId: '529664366719',
    projectId: 'weldai-b9b25',
    storageBucket: 'weldai-b9b25.firebasestorage.app',
    iosBundleId: 'com.example.firstly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe49PHpOcBBtB-Q01WM6BGpEqJDByIUQQ',
    appId: '1:529664366719:web:3d94bd0aa0b9dc7cd5074a',
    messagingSenderId: '529664366719',
    projectId: 'weldai-b9b25',
    authDomain: 'weldai-b9b25.firebaseapp.com',
    storageBucket: 'weldai-b9b25.firebasestorage.app',
    measurementId: 'G-Z6KN2WG8H2',
  );

}